import type { Freshness, QuestionDecision, SnapshotFacts, StoredCitation } from "@veriflow/answers";
import type { AnswerKind, FlowAnswer } from "@veriflow/flow-answer";
import { proposedModulesOf } from "@veriflow/flow-answer";
import { buildFlowOverlay, type OverlayMatching } from "@veriflow/diagram";
import { OVERLAY_MARKER_NOTE, renderMermaid } from "./mermaid.js";

/**
 * The document a team reads in review, on a machine where VeriFlow is not installed. Everything in
 * it is repository-relative and generated from the stored answer alone: no absolute path, no
 * machine-specific value, and no clock — so re-exporting an unchanged answer produces no diff.
 */

export interface DocumentInput {
  answerId: string;
  question: string;
  answer: FlowAnswer;
  citations: readonly StoredCitation[];
  snapshot: SnapshotFacts;
  freshness: Freshness;
  /** Overrides the body's own `kind`. Falls back to it, then to `observed`. */
  kind?: AnswerKind;
  /**
   * Who settled which question, by question id. The decision itself is already on the answer — this
   * is the attribution beside it, which lives on the correction row rather than in the body.
   */
  decisions?: ReadonlyMap<string, QuestionDecision>;
  /** Merged over the defaults by the caller, so the project's convention wins. */
  frontmatter: Record<string, string>;
  /** What the reader should run to check this document against the code. */
  command?: string;
  /** The observed parent and matcher output when a proposal should be reviewed as one overlay. */
  overlay?: { base: FlowAnswer; matching: OverlayMatching };
}

export interface Document {
  text: string;
  diagramParticipants: number;
}

const FRESHNESS_RULE: Record<string, string> = {
  fresh: "no file this document cites has changed since it was written",
  drifted: "something it cites has changed, but every reference still locates",
  stale: "at least one reference no longer locates — re-verify before trusting it",
  broken: "the flow's first steps are gone — this document describes code that is no longer entered here",
};

export function renderDocument(input: DocumentInput): Document {
  const { answer } = input;
  const overlay = input.overlay ? buildFlowOverlay(input.overlay.base, answer, input.overlay.matching) : undefined;
  const diagram = overlay
    ? renderMermaid(overlay.answer, {
        stepChanges: overlay.stepChanges,
        laneChanges: overlay.laneChanges,
      })
    : renderMermaid(answer);
  const out: string[] = [];

  /* ----------------------------------------------------------- frontmatter */

  // `last-reviewed` is the answer's own date, never today's: a document that rewrites itself every
  // time it is exported would produce a diff on a day nobody touched the code.
  const front: Record<string, string> = {
    ...input.frontmatter,
    "last-reviewed": (input.snapshot.capturedAt || "").slice(0, 10),
    "veriflow-answer": input.answerId,
    "veriflow-snapshot": input.snapshot.commit ?? input.snapshot.id.slice(0, 12),
  };
  out.push("---");
  for (const [key, value] of Object.entries(front)) out.push(`${key}: ${value}`);
  out.push("---", "");

  /* ---------------------------------------------------------------- header */

  out.push(`# ${answer.title}`, "");
  out.push(
    `> Generated by VeriFlow from stored answer \`${input.answerId.slice(0, 8)}\`. Edit the answer and`,
    `> re-export rather than editing this file: an export refuses to overwrite changes it did not make.`,
    "",
  );

  // Said once, at the top, in the place a reader cannot skip. A document that describes a change
  // somebody wants and reads like a description of the code is the most expensive kind of wrong.
  const kind: AnswerKind = input.kind ?? answer.kind ?? "observed";
  if (kind === "proposed") {
    const proposed = proposedModulesOf(answer).filter((m) => !m.existsInRegistry);
    out.push(
      `> **This is a proposal, not a description.** It says what the flow *should* do, not what the`,
      `> code does today. References with no line number name code that has not been written.`,
      ...(proposed.length
        ? [
            `> It would add ${proposed.length} module${proposed.length === 1 ? "" : "s"} the repository does`,
            `> not have: ${proposed.map((m) => `\`${m.root}\``).join(", ")}.`,
          ]
        : []),
      "",
    );
  }

  out.push(`**Question asked** — ${input.question}`, "");

  const f = input.freshness;
  out.push(
    `**Measured against** commit \`${input.snapshot.commit ?? "none"}\`` +
      `${input.snapshot.branch ? ` on \`${input.snapshot.branch}\`` : ""}, captured ` +
      `${input.snapshot.capturedAt.slice(0, 16).replace("T", " ")}` +
      `${input.snapshot.dirtyAtCapture ? " (the working tree was dirty at capture)" : ""}.`,
    "",
  );
  out.push(
    `**Freshness at export** — \`${f.state}\`: ${FRESHNESS_RULE[f.state] ?? ""}. ` +
      `${f.citedFilesChanged} of ${f.citedFiles} cited files had changed` +
      `${f.citedFilesMissing > 0 ? `, ${f.citedFilesMissing} of them gone` : ""}.`,
    "",
  );
  if (f.state === "stale" || f.state === "broken") {
    out.push(
      `> ⚠ This document was exported from a \`${f.state}\` answer. The claims below were true of the`,
      `> code at the commit above and at least one of them can no longer be located in the code as it`,
      `> is now. Re-verify before relying on it.`,
      "",
    );
  }

  /* --------------------------------------------------------------- diagram */

  out.push("## The flow", "");
  out.push("```mermaid", diagram.text, "```", "");
  if (diagram.overlay) out.push(...OVERLAY_MARKER_NOTE);
  if (diagram.legend.length > 0) {
    out.push("| arrow | meaning |", "|---|---|");
    for (const item of diagram.legend) out.push(`| \`${item.arrow}\` | ${item.legend} |`);
    out.push("");
  }

  /* ---------------------------------------------------------------- phases */

  out.push("## Step by step", "");
  const phases = [...answer.phases].sort((a, b) => a.ordinal - b.ordinal);
  const laneName = new Map(answer.lanes.map((l) => [l.id, l.name]));
  const name = (id: string): string => laneName.get(id) ?? id;

  // Numbered by position, not by the recorded ordinal: an answer whose phases start at 1, or which
  // skips one, would otherwise produce a document that starts at "2." and looks like it lost a page.
  let number = 0;
  for (const phase of phases) {
    const steps = answer.steps.filter((s) => s.phaseId === phase.id);
    if (steps.length === 0) continue;
    number += 1;
    out.push(`### ${number}. ${phase.title}`, "");
    out.push("| # | From → To | What happens | Evidence |", "|---|---|---|---|");
    steps.forEach((step, i) => {
      out.push(
        `| ${i + 1} | ${tableCell(name(step.from))} → ${tableCell(name(step.to))} | ${tableCell(step.label)} | ${refs(step.citations)} |`,
      );
    });
    out.push("");
    for (const step of steps) {
      if (step.reasoning) out.push(`- **${tableCell(step.label)}** — ${tableCell(step.reasoning)}`);
    }
    if (steps.some((s) => s.reasoning)) out.push("");
  }

  /* -------------------------------------------------------------- branches */

  out.push("## Where it can end", "");
  if (answer.branches.length === 0) {
    out.push("This answer records no alternative outcome.", "");
  } else {
    out.push(
      `${answer.branches.length} alternative outcome${answer.branches.length === 1 ? "" : "s"} besides`,
      `the happy path. Each states the invariant it protects — that is the list a change must not break.`,
      "",
    );
    const stepLabel = new Map(answer.steps.map((s) => [s.id, s.label]));
    for (const branch of answer.branches) {
      out.push(`### ${branch.title}`, "");
      out.push(`**Protects** — ${tableCell(branch.invariant)}  `);
      out.push(
        `**Leaves from** — ${tableCell(stepLabel.get(branch.forkStepId) ?? branch.forkStepId)} · **tone** \`${branch.tone}\``,
        "",
      );
      if (branch.steps.length > 0) {
        out.push("| # | From → To | What happens | Evidence |", "|---|---|---|---|");
        branch.steps.forEach((step, i) => {
          out.push(
            `| ${i + 1} | ${tableCell(name(step.from))} → ${tableCell(name(step.to))} | ${tableCell(step.label)} | ${refs(step.citations)} |`,
          );
        });
        out.push("");
      }
    }
  }

  /* --------------------------------------------------------------- modules */

  out.push("## Module contracts", "");
  if (answer.moduleEdges.length === 0) {
    out.push("This answer declared no module edge.", "");
  } else {
    out.push("| From | To | What crosses it | Kind | Derived how |", "|---|---|---|---|---|");
    for (const edge of answer.moduleEdges) {
      out.push(
        `| \`${edge.from}\` | \`${edge.to}\` | ${tableCell(edge.contract)} | ${edge.kind} | ` +
          `${edge.inferred ? `inferred — ${tableCell(edge.rule ?? "rule not recorded")}` : "observed at a call site"} |`,
      );
    }
    out.push("");
  }

  /* -------------------------------------------------------------- external */

  out.push("## Outside the repository", "");
  if (answer.externalSystems.length === 0) {
    out.push("This flow declared no external system.", "");
  } else {
    out.push("| System | Boundary enforced at | When it fails |", "|---|---|---|");
    for (const system of answer.externalSystems) {
      out.push(`| ${tableCell(system.name)} | \`${system.boundaryPath}\` | ${tableCell(system.failureBehavior)} |`);
    }
    out.push("");
  }

  /* -------------------------------------------------------- open questions */

  out.push("## What the repository could not answer", "");
  if (answer.openQuestions.length === 0) {
    out.push("Nothing was left open.", "");
  } else {
    const undecided = answer.openQuestions.filter((q) => !q.decision).length;
    if (undecided !== answer.openQuestions.length) {
      out.push(
        `${undecided} of ${answer.openQuestions.length} still open; the rest were decided by a person and`,
        `carry who decided and when.`,
        "",
      );
    }
    for (const question of answer.openQuestions) {
      out.push(`- ${question.blocking ? "**(blocking)** " : ""}${tableCell(question.question)}`);
      if (question.attemptedEvidence.length > 0) {
        out.push(`  - examined: ${question.attemptedEvidence.map((e) => `\`${e}\``).join(", ")}`);
      }
      // The question stays above the decision rather than being replaced by it: a reader six months
      // out needs to know what was uncertain, not only how it was settled.
      if (question.decision) {
        const decided = input.decisions?.get(question.id);
        const by = decided ? ` — ${tableCell(decided.author)}, ${decided.decidedAt.slice(0, 10)}` : "";
        out.push(`  - **decided:** ${tableCell(question.decision)}${by}`);
        if (decided?.rationale) out.push(`  - because: ${tableCell(decided.rationale)}`);
      }
    }
    out.push("");
  }

  /* ------------------------------------------------------------ references */

  out.push("## References", "");
  const seen = new Map<string, { path: string; line: number | null; symbol?: string; state: string }>();
  for (const citation of input.citations) {
    const key = `${citation.path}:${citation.line ?? "intent"}`;
    if (seen.has(key)) continue;
    seen.set(key, {
      path: citation.path,
      line: citation.line,
      ...(citation.symbol ? { symbol: citation.symbol } : {}),
      state: citation.state,
    });
  }
  const references = [...seen.values()].sort((a, b) =>
    a.path === b.path ? (a.line ?? 0) - (b.line ?? 0) : a.path < b.path ? -1 : 1,
  );
  const intent = references.filter((r) => r.line === null || r.line === undefined).length;
  if (references.length === 0) {
    out.push("This answer carries no citation.", "");
  } else {
    out.push(
      `${references.length} distinct reference${references.length === 1 ? "" : "s"}, each labelled with`,
      `whether it verified when the answer was submitted. Paths are repository-relative.`,
      "",
    );
    if (intent > 0) {
      // Stated rather than left to be inferred from a blank line number. A reader who takes an
      // intent reference for an observed one has been told the code does something it does not do.
      out.push(
        `${intent} of them ${intent === 1 ? "is" : "are"} an **intent** reference: a path this proposal`,
        `would put code at, which does not exist yet and therefore verified against nothing.`,
        "",
      );
    }
    out.push("| Reference | Symbol | At submit time |", "|---|---|---|");
    for (const reference of references) {
      const where =
        reference.line === null || reference.line === undefined
          ? `\`${reference.path}\` *(no line — not written yet)*`
          : `\`${reference.path}:${reference.line}\``;
      out.push(`| ${where} | ${reference.symbol ? `\`${reference.symbol}\`` : "—"} | ${reference.state} |`);
    }
    out.push("");
  }

  out.push("---", "");
  out.push(
    `Re-check this document against the code with \`${input.command ?? `veriflow verify ${input.answerId.slice(0, 8)}`}\`,`,
    `and regenerate it with \`veriflow export ${input.answerId.slice(0, 8)} --doc\`.`,
    "",
  );

  return { text: out.join("\n"), diagramParticipants: diagram.participants };
}

/** A markdown table cell: a pipe or a newline in free text would end the row early. */
export function tableCell(text: string): string {
  return text.replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();
}

/**
 * A citation with no line is a claim about code that does not exist yet, and the document says so
 * in the cell rather than printing `path:undefined`. The marker is the same word the envelope, the
 * CLI and the browser use, so a reader who has seen one has seen them all.
 */
function refs(citations: ReadonlyArray<{ path: string; line?: number; plannedPath?: string }>): string {
  if (citations.length === 0) return "—";
  return citations
    .map((c) =>
      c.line === undefined
        ? `\`${c.plannedPath ?? c.path}\` *(intent)*`
        : `\`${c.path}:${c.line}\``,
    )
    .join("<br>");
}

/** `A booking is refunded` → `a-booking-is-refunded`. The file name an export defaults to. */
export function slugify(title: string): string {
  const ascii = title
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return (ascii || "flow").slice(0, 60).replace(/-+$/, "");
}
